### ISSUE TITLE
Improve API for interacting with fxa-python-client

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/fxa-python-client#26]
This package is excellent - thank you very much for it. The one thing that bothers me a bit is that I have to execute commands against it (e.g., via `subprocess.check_call`), as opposed to being able to just instantiate an object and call methods on it. The latter is the way we generally interact with packages that we use.

Is there any interest in improving the API so that it can be simple method calls, instead of having to spawn a process to execute a command? I'm not suggesting doing away with the command interface, as I wouldn't want to break other projects that use it, but rather adding a object/method interface as well.

**Comment by rfk** [comment]
Closing, as this repo is now marked archived
