### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mcatanzaro** [mozilla/fxa-python-client#29]
Hi, I couldn't find any license for this project. There is no COPYING or LICENSE file, and no license blocks in the sources. Please consider licensing this code under some free software license (e.g. MPL) so it can be used. Thanks.

**Comment by warner** [comment]
I'm guessing a mozilla person would need to have the final word (@rfk?), but if I'd thought about it when I first wrote this code, I'd have either slapped an MIT, MPL, or CC-0 on it.

**Comment by rfk** [comment]
@warner 👋 

Let's make it MPL, for consistency with the rest of the FxA ecosystem
